import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createDemoHandler} from '../api/delivery-demo.js';
test('rider photo picker handles cancellation, decode retry, automatic start and completion without real GPS or order API',async()=>{
 const db=new Map(),requests=[],nodes=new Map(),created=[];let n=0;
 const api=createDemoHandler({ready:()=>true,rate:async()=>true,random:()=>String(++n).padStart(48,'a'),get:async k=>structuredClone(db.get(k)),write:async(k,v)=>db.set(k,structuredClone(v))});
 class Element{constructor(){this.events={};this.classList={add(){},remove(){},contains(){return true}};this.disabled=false}addEventListener(e,fn){this.events[e]=fn}prepend(){}appendChild(){}replaceChildren(){}after(){}removeAttribute(){}setAttribute(){}click(){if(!this.disabled)return this.events.click?.()}}
 const el=id=>{if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id)};
 const c=vm.createContext({console,URLSearchParams,AbortSignal,Date,Image:Element,location:{search:'?demo=1',hash:''},history:{replaceState(){}},navigator:{get geolocation(){throw Error('Demo must not use GPS')}},document:{getElementById:el,querySelector:el,createElement(){const e=new Element();created.push(e);return e},addEventListener(){}},confirm:()=>true,setInterval:()=>1,clearInterval(){},createRiderSheet:()=>({setActive(){}}),createRiderGoogleMap:()=>({async update(){return false},clear(){},fit(){}}),createDeliveryMap:()=>({update(){},clear(){},fit(){}}),decodeDeliveryRoute:()=>[],encodeDeliveryRoute:()=>'',fetch:async(url,o={})=>{requests.push(url);if(url==='/api/delivery?action=demo-route')return {ok:true,json:async()=>({destination:{lat:13.7463,lng:100.5346},route:null})};assert.match(url,/^\/api\/delivery-demo/);const q=Object.fromEntries(new URLSearchParams(url.split('?')[1]));const r={code:200,setHeader(){},status(s){this.code=s;return this},json(data){this.data=data}};await api({method:o.method||'GET',query:q,body:o.body?JSON.parse(o.body):{},headers:{'x-demo-token':o.headers?.['X-Demo-Token']}},r);return {ok:r.code===200,json:async()=>r.data};}});c.window=c;c.addEventListener=()=>{};
 vm.runInContext(readFileSync(new URL('../driver-demo.js',import.meta.url),'utf8'),c);
 const html=readFileSync(new URL('../driver-delivery.html',import.meta.url),'utf8');vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],c);
 const drain=()=>new Promise(resolve=>setImmediate(resolve));await drain();assert.equal(el('start').disabled,true);
 await el('riderPrimaryAction').click();assert.equal(el('departureInput').disabled,false);await el('departureInput').events.change();assert.equal(vm.runInContext('started',c),false);
 vm.runInContext("prepareDeparture=async()=>{throw new Error('Could not read this photo. Choose a JPEG or PNG.');}",c);el('departureInput').files=[{type:'image/jpeg'}];await el('departureInput').events.change();assert.match(el('notice').textContent,/Could not read/);assert.equal(el('riderPrimaryAction').disabled,false);assert.equal(vm.runInContext('started',c),false);
 vm.runInContext("prepareDeparture=async()=> 'data:image/jpeg;base64,aGVsbG8='",c);await el('departureInput').events.change();await drain();assert.equal(el('start').disabled,true);assert.equal(el('riderPrimaryAction').textContent,'Delivered');assert.equal(vm.runInContext('started',c),true);assert.equal(el('pause').disabled,false);
 await el('pause').click();assert.equal(vm.runInContext('active',c),false);el('start').click();await drain();await el('riderPrimaryAction').click();assert.equal(vm.runInContext('ended',c),false);el('departureInput').files=[];await el('departureInput').events.change();assert.equal(vm.runInContext('ended',c),false);el('departureInput').files=[{type:'image/jpeg'}];await el('departureInput').events.change();assert.equal(vm.runInContext('ended',c),true);assert.equal(vm.runInContext('finished',c),true);assert.equal(el('riderPrimaryAction').textContent,'Delivered');assert.ok(created.some(e=>e.textContent==='Order DEMO-RIDER'));assert.ok(created.some(e=>e.textContent==='Sample sandwich (test only) × 1'));await el('riderPrimaryAction').click();assert.equal(el('riderPrimaryAction').textContent,'Delivered');assert.equal(el('riderPrimaryAction').disabled,true);assert.equal(el('start').disabled,true);assert.ok(created.some(e=>e.textContent==='Open linked customer demo'&&e.href.includes('session=')&&e.className==='hidden'));assert.ok(!created.some(e=>/sample departure|next sample|Restart rider/.test(e.textContent||'')));assert.match(html,/<input id="departureInput" type="file" accept="image\/\*" aria-label=/);assert.doesNotMatch(html,/capture="user"|Photo before starting delivery|Voice navigation in Google Maps/);assert.ok(requests.every(u=>u.startsWith('/api/delivery-demo')||u==='/api/delivery?action=demo-route'));
});

