import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemoHandler} from '../api/delivery-demo.js';
function fixture(){const db=new Map();let n=0;const handler=createDemoHandler({ready:()=>true,rate:async()=>true,random:()=>String(++n).padStart(48,'a'),get:async k=>structuredClone(db.get(k)),write:async(k,v)=>db.set(k,structuredClone(v))});async function call(body={},token,method='POST'){const res={code:200,setHeader(){},status(c){this.code=c;return this},json(j){this.data=j;return this}};await handler({method,body,query:body,headers:{'x-demo-token':token}},res);return res;}return {db,call};}
test('paired demo uses distinct tokens and customer cannot mutate sample session',async()=>{const f=fixture(),s=(await f.call({action:'create'})).data;assert.notEqual(s.riderToken,s.customerToken);assert.equal((await f.call({id:s.id,role:'customer',action:'start'},s.customerToken)).code,403);assert.equal((await f.call({id:s.id,role:'rider'},s.customerToken,'GET')).code,403);const r=await f.call({id:s.id},s.customerToken,'GET');assert.equal(r.data.status,'preparing');assert.equal(r.data.riderToken,undefined);});
test('rider actions appear in customer view without storing real GPS or uploaded photo',async()=>{const f=fixture(),s=(await f.call({action:'create'})).data;const action=a=>f.call({id:s.id,role:'rider',action:a,deliveryPhoto:a==='complete',photo:'PRIVATE PHOTO',location:{lat:90,lng:180}},s.riderToken);assert.equal((await action('start')).code,400);await action('photo');await action('start');await action('move');let c=(await f.call({id:s.id},s.customerToken,'GET')).data;assert.equal(c.status,'on_the_way');assert.equal(c.index,1);assert.equal(c.photo,true);await action('pause');assert.equal((await action('move')).code,409);await action('start');await action('complete');c=(await f.call({id:s.id},s.customerToken,'GET')).data;assert.equal(c.status,'completed');assert.equal(c.photo,false);assert.equal((await action('start')).code,409);assert.ok([...f.db.keys()].every(k=>k.startsWith('delivery-sample:')));assert.doesNotMatch(JSON.stringify([...f.db]),/PRIVATE PHOTO|latitude|location/);});
test('demo expires and rejects absent tokens',async()=>{const f=fixture(),s=(await f.call({action:'create'})).data;assert.equal((await f.call({id:s.id},undefined,'GET')).code,403);f.db.get('delivery-sample:'+s.id).expiresAt=Date.now()-1;assert.equal((await f.call({id:s.id},s.customerToken,'GET')).code,404);});
test('sample session creation fails when persistent storage is unavailable',async()=>{const handler=createDemoHandler({ready:()=>false,rate:async()=>true});const r={setHeader(){},status(c){this.code=c;return this},json(){}};await handler({method:'POST',body:{action:'create'}},r);assert.equal(r.code,503);});

