import { getMenu } from "./_menu.js";
import { isPublicProduct, productUrl } from "./_seo.js";

const buckets=new Map(),cache=new Map();
const SYNONYMS={bud:["flower","flowers","strain"],weed:["flower","flowers","cannabis"],joint:["pre-roll","preroll","blunt"],preroll:["pre-roll","joint"],calm:["relax","relaxed","sleepy"],sleep:["sleepy","relax","indica"],energy:["energetic","uplifted","sativa"],cbd:["wellness","cbd"],food:["food","drink","burger"],cheap:["budget","value"]};
function clean(v,max=160){return String(v??"").trim().slice(0,max)}
function norm(v){return clean(v,1000).normalize("NFKD").toLowerCase().replace(/[^\p{Letter}\p{Number}.]+/gu," ").trim()}
function words(v){return norm(v).split(/\s+/).filter(Boolean)}
function priceOf(p){const tiers=Array.isArray(p?.priceTiers)?p.priceTiers:[];return Number(tiers[0]?.price??p?.price)||0}
function imageOf(p){const images=Array.isArray(p?.images)?p.images:[];return clean(p?.image||p?.imageUrl||p?.image_url||p?.img||p?.picture||p?.photo||p?.thumbnail||images[0],2000)}
function gramsOf(p){const saved=Array.isArray(p?.gramOptions)?p.gramOptions:[];if(saved.length)return saved.map(Number).filter(Number.isFinite);return (Array.isArray(p?.priceTiers)?p.priceTiers:[]).map(t=>Number(t?.grams??t?.qty)).filter(n=>Number.isFinite(n)&&n>0)}
function fields(p){return{title:norm(p.name),category:norm(p.category),strain:norm(p.strain||p.strainName),type:norm(p.type||p.strainType||p.cannabisType),description:norm(p.description),effects:norm(Array.isArray(p.effects)?p.effects.join(" "):p.effects)}}
function expand(query,extra=[]){const set=new Set([...words(query),...extra.flatMap(words)]);[...set].forEach(w=>(SYNONYMS[w]||[]).forEach(x=>set.add(x)));return[...set].slice(0,24)}
function scoreProduct(p,query,terms){const f=fields(p),q=norm(query);let score=0;if(f.title===q)score+=120;if(f.title.startsWith(q))score+=65;if(f.title.includes(q))score+=45;if(f.strain.includes(q))score+=32;if(f.category.includes(q))score+=25;for(const t of terms){if(f.title.includes(t))score+=18;if(f.strain.includes(t))score+=14;if(f.category.includes(t))score+=10;if(f.type.includes(t))score+=9;if(f.effects.includes(t))score+=7;if(f.description.includes(t))score+=3}if(Number(p.stock)===0)score-=20;return score}
function result(p){return{id:clean(p.id||p.sku,140),name:clean(p.name,140),category:clean(p.category||"Other",80),strain:clean(p.strain||p.strainName,100),type:clean(p.type||p.strainType||p.cannabisType,80),description:clean(p.description,240),image:imageOf(p),price:priceOf(p),grams:gramsOf(p),stock:Number.isFinite(Number(p.stock))?Number(p.stock):null,url:productUrl(p)}}
function limited(req){const ip=clean(req.headers["x-forwarded-for"]||req.socket?.remoteAddress||"unknown",100).split(",")[0],now=Date.now(),b=buckets.get(ip);if(!b||now-b.start>60000){buckets.set(ip,{start:now,count:1});return false}b.count++;return b.count>30}
async function aiTerms(query,catalog){if(!process.env.OPENAI_API_KEY)return[];const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),1800);try{const names=catalog.slice(0,120).map(p=>[p.name,p.category,p.strain||p.strainName,p.type||p.strainType,Array.isArray(p.effects)?p.effects.join(" "):p.effects].filter(Boolean).join(" | ")).join("\n");const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.OPENAI_API_KEY},body:JSON.stringify({model:process.env.OPENAI_SEARCH_MODEL||"gpt-4.1-mini",max_output_tokens:100,input:"Return only JSON as {\"terms\":[\"...\"]}. Expand this shop search into at most 8 short catalog terms. Use only concepts supported by the supplied catalog. Never add medical claims, prices, or product names not present. Query: "+JSON.stringify(query)+"\nCatalog:\n"+names})});if(!response.ok)return[];const data=await response.json(),out=(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text).join("");const parsed=JSON.parse(out.replace(/^\x60\x60\x60(?:json)?|\x60\x60\x60$/g,"").trim());return Array.isArray(parsed.terms)?parsed.terms.map(x=>clean(x,40)).filter(Boolean).slice(0,8):[]}catch{return[]}finally{clearTimeout(timer)}}
export default async function handler(req,res){res.setHeader("Cache-Control","private, max-age=15, stale-while-revalidate=30");res.setHeader("X-Content-Type-Options","nosniff");if(req.method!=="GET")return res.status(405).json({error:"method not allowed"});if(limited(req))return res.status(429).json({error:"too many searches"});const query=clean(req.query?.q,120);if(query.length<2)return res.status(200).json({query,results:[],ai:false});const key=norm(query),cached=cache.get(key);if(cached&&Date.now()-cached.at<60000)return res.status(200).json(cached.value);try{const menu=await getMenu(),catalog=(Array.isArray(menu.data)?menu.data:[]).filter(isPublicProduct),extra=await aiTerms(query,catalog),terms=expand(query,extra),ranked=catalog.map(p=>({p,score:scoreProduct(p,query,terms)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(a.p.name).localeCompare(String(b.p.name))).slice(0,8).map(x=>result(x.p)),value={query,results:ranked,ai:extra.length>0};cache.set(key,{at:Date.now(),value});if(cache.size>200)cache.delete(cache.keys().next().value);return res.status(200).json(value)}catch{return res.status(503).json({error:"search unavailable",results:[]})}}
